💄Make button with hover effects but no animation
ashby-git/dear-coco pull request #24
Opened 2021-09-09 08:04 UTC by ashby-git

**What did you do?**
- Made a standard button, it has hover effects, no animation, and fills to size of parent container

**Screenshot**
![8  StandardButton - reg](https://user-images.githubusercontent.com/59023409/132647418-1be97718-5c6f-45ec-bd43-163d460adf5f.png)
![8  StandardButton - hover](https://user-images.githubusercontent.com/59023409/132647448-92f19788-ab39-45a1-8094-8c8dcf0b23f5.png)

**How to Check Feature/Bug Fix**
```
import './App.css';
import StandardButton from './components/standard-button/standard-button.component';

function App() {
  return (
    <div className="container">
      <div className='background'>

        <div className="stdButton-container">
          <StandardButton>商品ページへ</StandardButton>
        </div>

      </div>
    </div>
  );
}

export default App;
```

CSS
```
.background {

    height: 100vh;
    width: 100%;
    text-align: center;
    background-image: url(./assets/kv_bgimg.jpg);
    background-size: cover;
    /* background-attachment: fixed; */
    background-repeat: no-repeat;
    background-position: center; 

   }

.stdButton-container {
    position: relative;
    height: 10vh;
    width: 30vw;
    background-color: red;
}
```

**Link to the Design**
(https://xd.adobe.com/view/c0f0ee74-781d-434f-9960-3ff85a002849-95a3/specs/?fbclid=IwAR3bcz-BSXJGrgTXDSVBv0y-PYnSKaPM075W3UEhqyWRb_iHMHv7nu77Hq4)

2021-09-12 11:37 UTC, DanArcherOnline requested changes
use props to set height and width
`<div style={{ height: props.height, width: props.width }} className="wrapper">`
used like this
`<StandardButton width="300px" height="50px">商品ページへ</StandardButton>`

- move the styles that are in the app.css into the component styles css file - should just be the positioning (as width and height are props now)

2021-09-21 03:41 UTC, DanArcherOnline requested changes
turned out like this ↓

<img width="1680" alt="Screenshot 2021-09-21 at 12 36 26" src="https://user-images.githubusercontent.com/46483718/134107774-9c7d90b4-12c5-48be-bdcd-cc6588549376.png">

remember to update the code sample in the PR to test the related feature. I added in height and width myself, and did not add the CSS part (because as we discussed, styles should be encapsulated within the component, and not something to add when you want to use a component)

so double check this is working and update the sample code above so it can copy/paste it in to test it

2021-09-22 07:25 UTC, ashby-git commented
Updated app.js code example

2021-10-06 04:29 UTC, DanArcherOnline approved these changes

2021-10-06 04:29 UTC, DanArcherOnline commented on src/components/standard-button/standard-button.component.jsx
> +                <span>{props.children}</span>
not a big thing but I couldn't see a reason for the span.
try to use minimal html tags all the time.
If its not necessary, consider removing the span tag.

2021-10-06 04:29 UTC, merged